In [3]:
from os import environ
from os.path import join, splitext

input_folder = environ.get(
    'CROSSCOMPUTE_INPUT_FOLDER', 'tests/standard/input')
output_folder = environ.get(
    'CROSSCOMPUTE_OUTPUT_FOLDER', 'tests/standard/output')

In [9]:
import pandas as pd

input_data_path = join(input_folder, 'input-data.csv')
output_data_path = join(output_folder, 'output-data.json')

input_df = pd.read_csv(input_data_path, index_col='id')

input_df.to_json(output_data_path, orient='index')

input_df

    firstname  lastname                        email      profession
id
10     Roxane    Joseph     Roxane.Joseph@random.com          worker
11     Dorice      Ajay       Dorice.Ajay@random.com          doctor
12      Tonia   Eachern     Tonia.Eachern@random.com     firefighter
13   Gerianna     Niles    Gerianna.Niles@random.com     firefighter
14  Harrietta    Kirbee  Harrietta.Kirbee@random.com     firefighter
15    Melodie    Nerita    Melodie.Nerita@random.com          worker
16      Nyssa     Ogren       Nyssa.Ogren@random.com  police officer
17     Agathe    Chinua     Agathe.Chinua@random.com  police officer
18    Emelina  Arathorn  Emelina.Arathorn@random.com       developer
19      Elena   Granoff     Elena.Granoff@random.com          worker